[project]
name = "brrr"
version = "0.1.1dev"
description = "Horizontally scalable workflow scheduling with pluggable backends"
authors = [
    { name = "Robin", email = "robin.lewis@anterior.com" },
    { name = "Jesse Zwaan", email = "j.k.zwaan@gmail.com" },
    { name = "Anterior", email = "tech@anterior.com" },
]
requires-python = "<4,>=3.12"
dependencies = [
    "bencode-py>=4.0.0",
]

[project.urls]
homepage = "https://github.com/cohelm/brrr"

[dependency-groups]
dev = [
    "pyright>=1.1.389",
    "redis>=5.2.0",
    "ruff>=0.8.1",
    "pytest>=8.3.4",
    "aioboto3>=13.3.0",
    "types-aioboto3[essential]>=13.3.0.post1",
    "pytest-asyncio>=0.25.0",
    "aiohttp>=3.11.11",
    "pytest-timeout>=2.3.1",
    "types-redis>=4.6.0.20241004",
    "pytest-stub>=1.1.0",
    "types-aiobotocore-dynamodb>=2.18.0",
    "asyncio-redis>=0.16.0",
    "mypy>=1.15.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
asyncio_mode = "auto"
timeout = 10
markers = ["dependencies: requires external store / queue dependencies running"]
